/*
  simple translation helper
  - scans for `data-i18n` attributes and replaces content
  - contains a dictionary for each supported lang
  - auto-detects language via geolocation/IP and user preference
*/

const translations = {
  en: {
    "nav": {
      "signin": "Sign-in",
      "signup": "Sign-up",
      "about": "About us",
      "services": "Services",
      "support": "Support",
      "dashboard": "Dashboard",
      "transactions": "Transactions",
      "transaction": "Transaction",
      "transfer": "Transfer",
      "transfers": "Transfers",
      "settings": "Settings",
      "logout": "Logout"
    },
    "lang": {
      "label": "Language:"
    },
    "offers": {
      "title": "What we offer:",
      "encryption": "Advanced encryption to keep transactions safe.",
      "monitoring": "Real-time fraud monitoring with instant alerts.",
      "trackrecord": "Decades of proven track record in the banking industry.",
      "network": "Global network of branches/ATMs for easy access.",
      "service": "24/7 customer service with dedicated relationship managers.",
      "advice": "Personalized financial advice from certified experts.",
      "rewards": "Exclusive rewards & benefits tailored to lifestyle.",
      "approvals": "Fast approvals & easy onboarding for new accounts.",
      "fees": "Clear, upfront fees with no hidden charges."
    },
    "services": {
      "title": "Our Services include:",
      "personal": "Personal Banking",
      "investments": "Investments Services",
      "pension": "Pension Funds"
    },
    "footer": {
      "contact": "Contact Us",
      "email": "Email: <a href=\"mailto:unitedbnk@support.com\">unitedbnk@support.com</a>",
      "copyright": "&copy; 2026 United Bank. All rights reserved.",
      "privacy": "Privacy Policy",
      "terms": "Terms of Service",
      "contactLink": "Contact Us"
    },
    "signin": {
      "title": "Sign In to Your Account",
      "username": "Username:",
      "password": "Password:",
      "forgot": "Forgot password?",
      "submit": "Sign In"
    },
    "signup": {
      "title": "Create an Account",
      "tagline": "Banking without compromise — your gateway to prestige, security, and growth.",
      "email": "Email:",
      "password": "Password:",
      "confirm": "Confirm Password:",
      "submit": "Sign Up",
      "agreement": "By signing up, you agree to our <a href=\"\">Terms of Service</a> and <a href=\"\">Privacy Policy</a>."
    },
    "transfer": {
      "senderTitle": "Sender Details",
      "name": "Name:",
      "account": "Account Number:",
      "mainBalance": "Main Balance:",
      "savingsBalance": "Savings Balance:",
      "cardBalance": "Card Balance:",
      "title": "Transfer Funds",
      "desc": "Send money securely to another bank account.",
      "fromAccount": "Choose Account",
      "select": "Select Account",
      "mainAcc": "Main Account",
      "savingsAcc": "Savings Account",
      "cardAcc": "Card",
      "recipientBank": "Recipient Bank",
      "recipientName": "Recipient Name",
      "recipientAccount": "Recipient Account Number",
      "amount": "Amount ($)",
      "description": "Description",
      "send": "Send",
      "pending": "Transaction pending, waiting for approval"
    },
    "trans": {
      "title": "Transaction History",
      "desc": "View all your account activity.",
      "filter": "Filter Transactions",
      "allTypes": "All Types",
      "credit": "Credit",
      "debit": "Debit",
      "allStatus": "All Status",
      "completed": "Completed",
      "pending": "Pending",
      "failed": "Failed",
      "apply": "Apply Filter",
      "allTrans": "All Transactions"
    },
    "dashboard": {
      "welcome": "Welcome back",
      "summary": "Your financial summary at a glance.",
      "accountBal": "Account Balance",
      "savingsBal": "Savings Balance",
      "creditCard": "Credit Card",
      "due": "due",
      "quickActions": "Quick Actions",
      "transfer": "Transfer Funds",
      "payBills": "Pay Bills",
      "viewAccounts": "View Accounts",
      "recentTrans": "Recent Transactions"
    },
    "about": {
      "title": "About United Bank"
    },
    "receipt": {
      "headquarters": "Corporate Headquarters",
      "title": "OFFICIAL TRANSACTION RECEIPT",
      "subtitle": "System Generated Confirmation",
      "ref": "Transaction Reference:",
      "email": "Sender Email:",
      "fromAccount": "From Account:",
      "recipientName": "Recipient Name:",
      "recipientBank": "Recipient Bank:",
      "recipientAccount": "Recipient Account:",
      "amount": "Amount:",
      "description": "Description:",
      "date": "Date & Time:",
      "status": "Status:",
      "signatory": "Authorized Signatory",
      "verified": "DIGITALLY VERIFIED",
      "legal": "This document is electronically generated by United Bank's core banking system. No physical signature is required. If you did not authorize this transaction, contact customer support immediately.",
      "download": "Download Receipt"
    },
    "admin": {
      "dashboard": "Dashboard",
      "users": "Users",
      "transactions": "Transactions",
      "reports": "Reports",
      "settings": "Settings",
      "welcome": "Welcome, Admin",
      "overview": "Quick overview of the bank's system status."
    },
    "adminTrans": {
      "title": "Admin Panel - All Transactions"
    },
    "userDetails": {
      "title": "User Details"
    },
    "userList": {
      "title": "All Registered Users",
      "desc": "Below is the list of all users in the system."
    }
  },
  es: {
    "nav": {
      "signin": "Iniciar sesión",
      "signup": "Registrarse",
      "about": "Sobre nosotros",
      "services": "Servicios",
      "support": "Soporte",
      "dashboard": "Panel",
      "transactions": "Transacciones",
      "transaction": "Transacción",
      "transfer": "Transferir",
      "transfers": "Transferencias",
      "settings": "Configuración",
      "logout": "Cerrar sesión"
    },
    "lang": {
      "label": "Idioma:"
    },
    "offers": {
      "title": "Lo que ofrecemos:",
      "encryption": "Cifrado avanzado para mantener las transacciones seguras.",
      "monitoring": "Monitoreo de fraude en tiempo real con alertas instantáneas.",
      "trackrecord": "Décadas de trayectoria comprobada en la industria bancaria.",
      "network": "Red global de sucursales/ATMs para fácil acceso.",
      "service": "Servicio al cliente 24/7 con gerentes de relaciones dedicados.",
      "advice": "Consejos financieros personalizados de expertos certificados.",
      "rewards": "Recompensas y beneficios exclusivos adaptados al estilo de vida.",
      "approvals": "Aprobaciones rápidas y fácil incorporación para nuevas cuentas.",
      "fees": "Tarifas claras y por adelantado sin cargos ocultos."
    },
    "services": {
      "title": "Nuestros servicios incluyen:",
      "personal": "Banca Personal",
      "investments": "Servicios de Inversión",
      "pension": "Fondos de Pensiones"
    },
    "footer": {
      "contact": "Contáctenos",
      "email": "Correo: <a href=\"mailto:unitedbnk@support.com\">unitedbnk@support.com</a>",
      "copyright": "&copy; 2026 United Bank. Todos los derechos reservados.",
      "privacy": "Política de Privacidad",
      "terms": "Términos del Servicio",
      "contactLink": "Contáctenos"
    },
    "signin": {
      "title": "Inicia sesión en tu cuenta",
      "username": "Nombre de usuario:",
      "password": "Contraseña:",
      "forgot": "¿Olvidaste tu contraseña?",
      "submit": "Iniciar sesión"
    },
    "signup": {
      "title": "Crear una cuenta",
      "tagline": "Banca sin compromiso: su puerta de entrada al prestigio, la seguridad y el crecimiento.",
      "email": "Correo electrónico:",
      "password": "Contraseña:",
      "confirm": "Confirmar contraseña:",
      "submit": "Regístrate",
      "agreement": "Al registrarte, aceptas nuestros <a href=\"\">Términos del Servicio</a> y <a href=\"\">Política de Privacidad</a>."
    },
    "transfer": {
      "senderTitle": "Detalles del Remitente",
      "name": "Nombre:",
      "account": "Número de Cuenta:",
      "mainBalance": "Saldo Principal:",
      "savingsBalance": "Saldo de Ahorros:",
      "cardBalance": "Saldo de Tarjeta:",
      "title": "Transferir Fondos",
      "desc": "Envía dinero de forma segura a otra cuenta bancaria.",
      "fromAccount": "Selecciona Cuenta",
      "select": "Seleccionar Cuenta",
      "mainAcc": "Cuenta Principal",
      "savingsAcc": "Cuenta de Ahorros",
      "cardAcc": "Tarjeta",
      "recipientBank": "Banco del Destinatario",
      "recipientName": "Nombre del Destinatario",
      "recipientAccount": "Número de Cuenta del Destinatario",
      "amount": "Monto ($)",
      "description": "Descripción",
      "send": "Enviar",
      "pending": "Transacción pendiente, esperando aprobación"
    },
    "trans": {
      "title": "Historial de Transacciones",
      "desc": "Ver toda tu actividad de cuenta.",
      "filter": "Filtrar Transacciones",
      "allTypes": "Todos los Tipos",
      "credit": "Crédito",
      "debit": "Débito",
      "allStatus": "Todos los Estados",
      "completed": "Completado",
      "pending": "Pendiente",
      "failed": "Fallido",
      "apply": "Aplicar Filtro",
      "allTrans": "Todas las Transacciones"
    },
    "dashboard": {
      "welcome": "Bienvenido de vuelta",
      "summary": "Tu resumen financiero de un vistazo.",
      "accountBal": "Saldo de Cuenta",
      "savingsBal": "Saldo de Ahorros",
      "creditCard": "Tarjeta de Crédito",
      "due": "debido",
      "quickActions": "Acciones Rápidas",
      "transfer": "Transferir Fondos",
      "payBills": "Pagar Facturas",
      "viewAccounts": "Ver Cuentas",
      "recentTrans": "Transacciones Recientes"
    },
    "about": {
      "title": "Sobre United Bank"
    },
    "receipt": {
      "headquarters": "Sede Corporativa",
      "title": "RECIBO DE TRANSACCIÓN OFICIAL",
      "subtitle": "Confirmación Generada por el Sistema",
      "ref": "Referencia de Transacción:",
      "email": "Correo del Remitente:",
      "fromAccount": "Desde la Cuenta:",
      "recipientName": "Nombre del Destinatario:",
      "recipientBank": "Banco del Destinatario:",
      "recipientAccount": "Cuenta del Destinatario:",
      "amount": "Monto:",
      "description": "Descripción:",
      "date": "Fecha y Hora:",
      "status": "Estado:",
      "signatory": "Firmante Autorizado",
      "verified": "VERIFICADO DIGITALMENTE",
      "legal": "Este documento es generado electrónicamente por el sistema bancario de United Bank. No se requiere firma física. Si no autorizaste esta transacción, contacta a nuestro servicio al cliente de inmediato.",
      "download": "Descargar Recibo"
    },
    "admin": {
      "dashboard": "Panel",
      "users": "Usuarios",
      "transactions": "Transacciones",
      "reports": "Reportes",
      "settings": "Configuración",
      "welcome": "Bienvenido, Administrador",
      "overview": "Descripción general rápida del estado del sistema bancario."
    },
    "adminTrans": {
      "title": "Panel de Administración - Todas las Transacciones"
    },
    "userDetails": {
      "title": "Detalles del Usuario"
    },
    "userList": {
      "title": "Todos los Usuarios Registrados",
      "desc": "A continuación se muestra la lista de todos los usuarios en el sistema."
    }
  },

  fr: {
    "nav": {
      "signin": "Se connecter",
      "signup": "S'inscrire",
      "about": "À propos",
      "services": "Services",
      "support": "Assistance",
      "dashboard": "Tableau de bord",
      "transactions": "Transactions",
      "transaction": "Transaction",
      "transfer": "Virement",
      "transfers": "Virements",
      "settings": "Paramètres",
      "logout": "Déconnexion"
    },
    "lang": {
      "label": "Langue :"
    },
    "offers": {
      "title": "Ce que nous offrons :",
      "encryption": "Chiffrement avancé pour sécuriser les transactions.",
      "monitoring": "Surveillance de fraude en temps réel avec alertes instantanées.",
      "trackrecord": "Des décennies de parcours prouvé dans l'industrie bancaire.",
      "network": "Réseau mondial de succursales/ATM pour un accès facile.",
      "service": "Service client 24h/24 et 7j/7 avec des gestionnaires de relations dédiés.",
      "advice": "Conseils financiers personnalisés d'experts certifiés.",
      "rewards": "Récompenses et avantages exclusifs adaptés au style de vie.",
      "approvals": "Approvals rapides et intégration facile pour les nouveaux comptes.",
      "fees": "Frais clairs et à l'avance sans frais cachés."
    },
    "services": {
      "title": "Nos services comprennent :",
      "personal": "Services bancaires personnels",
      "investments": "Services d'investissement",
      "pension": "Fonds de pension"
    },
    "footer": {
      "contact": "Contactez-nous",
      "email": "E-mail : <a href=\"mailto:unitedbnk@support.com\">unitedbnk@support.com</a>",
      "copyright": "&copy; 2026 United Bank. Tous droits réservés.",
      "privacy": "Politique de confidentialité",
      "terms": "Conditions d'utilisation",
      "contactLink": "Contactez-nous"
    },
    "signin": {
      "title": "Connectez-vous à votre compte",
      "username": "Nom d'utilisateur:",
      "password": "Mot de passe:",
      "forgot": "Mot de passe oublié ?",
      "submit": "Se connecter"
    },
    "signup": {
      "title": "Créer un compte",
      "tagline": "Banque sans compromis : votre porte d'entrée vers le prestige, la sécurité et la croissance.",
      "email": "E-mail :",
      "password": "Mot de passe:",
      "confirm": "Confirmer le mot de passe:",
      "submit": "S'inscrire",
      "agreement": "En vous inscrivant, vous acceptez nos <a href=\"\">Conditions d'utilisation</a> et <a href=\"\">Politique de confidentialité</a>."    },
    "transfer": {
      "senderTitle": "Détails de l'Expéditeur",
      "name": "Nom :",
      "account": "Numéro de Compte :",
      "mainBalance": "Solde Principal :",
      "savingsBalance": "Solde d'Épargne :",
      "cardBalance": "Solde de Carte :",
      "title": "Effectuer un Virement",
      "desc": "Envoyez de l'argent de manière sécurisée à un autre compte bancaire.",
      "fromAccount": "Choisir un Compte",
      "select": "Sélectionner un Compte",
      "mainAcc": "Compte Principal",
      "savingsAcc": "Compte d'Épargne",
      "cardAcc": "Carte",
      "recipientBank": "Banque du Bénéficiaire",
      "recipientName": "Nom du Bénéficiaire",
      "recipientAccount": "Numéro de Compte du Bénéficiaire",
      "amount": "Montant ($)",
      "description": "Description",
      "send": "Envoyer",
      "pending": "Transaction en attente, en attente d'approbation"
    },
    "trans": {
      "title": "Historique des Transactions",
      "desc": "Consultez toute votre activité de compte.",
      "filter": "Filtrer les Transactions",
      "allTypes": "Tous les Types",
      "credit": "Crédit",
      "debit": "Débit",
      "allStatus": "Tous les Statuts",
      "completed": "Complété",
      "pending": "En Attente",
      "failed": "Échoué",
      "apply": "Appliquer le Filtre",
      "allTrans": "Toutes les Transactions"
    },
    "dashboard": {
      "welcome": "Bienvenue de retour",
      "summary": "Votre résumé financier d'un coup d'œil.",
      "accountBal": "Solde du Compte",
      "savingsBal": "Solde d'Épargne",
      "creditCard": "Carte de Crédit",
      "due": "dû",
      "quickActions": "Actions Rapides",
      "transfer": "Effectuer un Virement",
      "payBills": "Payer les Factures",
      "viewAccounts": "Voir les Comptes",
      "recentTrans": "Transactions Récentes"
    },
    "about": {
      "title": "À propos de United Bank"
    },
    "receipt": {
      "headquarters": "Siège Social",
      "title": "REÇU DE TRANSACTION OFFICIEL",
      "subtitle": "Confirmation Générée par le Système",
      "ref": "Référence de Transaction :",
      "email": "E-mail de l'Expéditeur :",
      "fromAccount": "Du Compte :",
      "recipientName": "Nom du Bénéficiaire :",
      "recipientBank": "Banque du Bénéficiaire :",
      "recipientAccount": "Compte du Bénéficiaire :",
      "amount": "Montant :",
      "description": "Description :",
      "date": "Date et Heure :",
      "status": "Statut :",
      "signatory": "Signataire Autorisé",
      "verified": "VÉRIFIÉ NUMÉRIQUEMENT",
      "legal": "Ce document est généré électroniquement par le système bancaire de United Bank. Aucune signature physique n'est requise. Si vous n'avez pas autorisé cette transaction, contactez immédiatement notre support client.",
      "download": "Télécharger le Reçu"
    },
    "admin": {
      "dashboard": "Tableau de bord",
      "users": "Utilisateurs",
      "transactions": "Transactions",
      "reports": "Rapports",
      "settings": "Paramètres",
      "welcome": "Bienvenue, Administrateur",
      "overview": "Aperçu rapide du statut du système bancaire."
    },
    "adminTrans": {
      "title": "Panneau d'Administration - Toutes les Transactions"
    },
    "userDetails": {
      "title": "Détails de l'Utilisateur"
    },
    "userList": {
      "title": "Tous les Utilisateurs Enregistrés",
      "desc": "Voici la liste de tous les utilisateurs du système."    }
  }
};

// helper to walk nested objects by dot notation key
function translateKey(obj, key) {
  return key.split('.').reduce((o, k) => (o && o[k] !== undefined ? o[k] : null), obj);
}

function applyTranslations(lang) {
  const nodes = document.querySelectorAll('[data-i18n]');
  nodes.forEach(node => {
    const key = node.getAttribute('data-i18n');
    const value = translateKey(translations[lang], key) || translateKey(translations.en, key) || '';
    node.innerHTML = value;
  });
}

function detectLanguage() {
  // first try navigator.language
  let lang = navigator.language && navigator.language.split('-')[0];
  if (lang && translations[lang]) return lang;

  // try geolocation-based lookup
  if (navigator.geolocation) {
    return new Promise(resolve => {
      navigator.geolocation.getCurrentPosition(
        pos => {
          const { latitude, longitude } = pos.coords;
          // simple country lookup using fetch to a free API
          fetch(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${latitude}&longitude=${longitude}&localityLanguage=en`)
            .then(r => r.json())
            .then(data => {
              const cc = (data.countryCode || '').toLowerCase();
              resolve(getLangFromCountryCode(cc));
            })
            .catch(() => resolve('en')); // fallback
        },
        () => resolve('en'),
        { timeout: 5000 }
      );
    });
  }

  // fallback to IP-based if geolocation not available
  return fetch('https://ipapi.co/json/')
    .then(r => r.json())
    .then(data => getLangFromCountryCode((data.country_code || '').toLowerCase()))
    .catch(() => 'en');
}

function getLangFromCountryCode(cc) {
  const map = {
    fr: 'fr',
    es: 'es',
    mx: 'es',
    ca: 'fr',
    us: 'en',
    gb: 'en',
    de: 'de' // future
  };
  return map[cc] || 'en';
}

// user can manually change
function setupSelector(lang) {
  const sel = document.getElementById('language-select');
  if (!sel) return;
  sel.value = lang;
  sel.addEventListener('change', e => {
    const chosen = e.target.value;
    applyTranslations(chosen);
    localStorage.setItem('preferredLang', chosen);
  });
}

// initialization
function initTranslations() {
  const stored = localStorage.getItem('preferredLang');
  if (stored && translations[stored]) {
    applyTranslations(stored);
    setupSelector(stored);
    return;
  }

  const detected = detectLanguage();
  if (detected instanceof Promise) {
    detected.then(lang => {
      applyTranslations(lang);
      setupSelector(lang);
    });
  } else {
    applyTranslations(detected);
    setupSelector(detected);
  }
}

// run once DOM is ready
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', initTranslations);
} else {
  initTranslations();
}
