/*
  simple translation helper
  - scans for `data-i18n` attributes and replaces content
  - contains a dictionary for each supported lang
  - auto-detects language via geolocation/IP and user preference
*/

const translations = {
  en: {
    "nav": {
      "signin": "Sign-in",
      "signup": "Sign-up",
      "about": "About us",
      "services": "Services",
      "support": "Support",
      "dashboard": "Dashboard",
      "transactions": "Transactions",
      "transaction": "Transaction",
      "transfer": "Transfer",
      "transfers": "Transfers",
      "settings": "Settings",
      "logout": "Logout"
    },
    "lang": {
      "label": "Language:"
    },
    "offers": {
      "title": "What we offer:",
      "encryption": "Advanced encryption to keep transactions safe.",
      "monitoring": "Real-time fraud monitoring with instant alerts.",
      "trackrecord": "Decades of proven track record in the banking industry.",
      "network": "Global network of branches/ATMs for easy access.",
      "service": "24/7 customer service with dedicated relationship managers.",
      "advice": "Personalized financial advice from certified experts.",
      "rewards": "Exclusive rewards & benefits tailored to lifestyle.",
      "approvals": "Fast approvals & easy onboarding for new accounts.",
      "fees": "Clear, upfront fees with no hidden charges."
    },
    "services": {
      "title": "Our Services include:",
      "personal": "Personal Banking",
      "investments": "Investments Services",
      "pension": "Pension Funds"
    },
    "footer": {
      "contact": "Contact Us",
      "email": "Email: <a href=\"mailto:unitedbnk@support.com\">unitedbnk@support.com</a>",
      "copyright": "&copy; 2026 United Bank. All rights reserved.",
      "privacy": "Privacy Policy",
      "terms": "Terms of Service",
      "contactLink": "Contact Us"
    },
    "signin": {
      "title": "Sign In to Your Account",
      "username": "Username:",
      "password": "Password:",
      "forgot": "Forgot password?",
      "submit": "Sign In"
    },
    "signup": {
      "title": "Create an Account",
      "tagline": "Banking without compromise — your gateway to prestige, security, and growth.",
      "email": "Email:",
      "password": "Password:",
      "confirm": "Confirm Password:",
      "submit": "Sign Up",
      "agreement": "By signing up, you agree to our <a href=\"\">Terms of Service</a> and <a href=\"\">Privacy Policy</a>."
    },
    "transfer": {
      "senderTitle": "Sender Details",
      "name": "Name:",
      "account": "Account Number:",
      "mainBalance": "Main Balance:",
      "savingsBalance": "Savings Balance:",
      "cardBalance": "Card Balance:",
      "title": "Transfer Funds",
      "desc": "Send money securely to another bank account.",
      "fromAccount": "Choose Account",
      "select": "Select Account",
      "mainAcc": "Main Account",
      "savingsAcc": "Savings Account",
      "cardAcc": "Card",
      "recipientBank": "Recipient Bank",
      "recipientName": "Recipient Name",
      "recipientAccount": "Recipient Account Number",
      "amount": "Amount ($)",
      "description": "Description",
      "send": "Send",
      "pending": "Transaction pending, waiting for approval"
    },
    "trans": {
      "title": "Transaction History",
      "desc": "View all your account activity.",
      "filter": "Filter Transactions",
      "allTypes": "All Types",
      "credit": "Credit",
      "debit": "Debit",
      "allStatus": "All Status",
      "completed": "Completed",
      "pending": "Pending",
      "failed": "Failed",
      "apply": "Apply Filter",
      "allTrans": "All Transactions"
    },
    "dashboard": {
      "welcome": "Welcome back",
      "summary": "Your financial summary at a glance.",
      "accountBal": "Account Balance",
      "savingsBal": "Savings Balance",
      "creditCard": "Credit Card",
      "due": "due",
      "quickActions": "Quick Actions",
      "transfer": "Transfer Funds",
      "payBills": "Pay Bills",
      "viewAccounts": "View Accounts",
      "recentTrans": "Recent Transactions"
    },
    "about": {
      "title": "About United Bank"
    },
    "receipt": {
      "headquarters": "Corporate Headquarters",
      "title": "OFFICIAL TRANSACTION RECEIPT",
      "subtitle": "System Generated Confirmation",
      "ref": "Transaction Reference:",
      "email": "Sender Email:",
      "fromAccount": "From Account:",
      "recipientName": "Recipient Name:",
      "recipientBank": "Recipient Bank:",
      "recipientAccount": "Recipient Account:",
      "amount": "Amount:",
      "description": "Description:",
      "date": "Date & Time:",
      "status": "Status:",
      "signatory": "Authorized Signatory",
      "verified": "DIGITALLY VERIFIED",
      "legal": "This document is electronically generated by United Bank's core banking system. No physical signature is required. If you did not authorize this transaction, contact customer support immediately.",
      "download": "Download Receipt"
    },
    "admin": {
      "dashboard": "Dashboard",
      "users": "Users",
      "transactions": "Transactions",
      "reports": "Reports",
      "settings": "Settings",
      "welcome": "Welcome, Admin",
      "overview": "Quick overview of the bank's system status."
    },
    "adminTrans": {
      "title": "Admin Panel - All Transactions"
    },
    "userDetails": {
      "title": "User Details"
    },
    "userList": {
      "title": "All Registered Users",
      "desc": "Below is the list of all users in the system."
    }
  },
  es: {
    "nav": {
      "signin": "Iniciar sesión",
      "signup": "Registrarse",
      "about": "Sobre nosotros",
      "services": "Servicios",
      "support": "Soporte",
      "dashboard": "Panel",
      "transactions": "Transacciones",
      "transaction": "Transacción",
      "transfer": "Transferir",
      "transfers": "Transferencias",
      "settings": "Configuración",
      "logout": "Cerrar sesión"
    },
    "lang": {
      "label": "Idioma:"
    },
    "offers": {
      "title": "Lo que ofrecemos:",
      "encryption": "Cifrado avanzado para mantener las transacciones seguras.",
      "monitoring": "Monitoreo de fraude en tiempo real con alertas instantáneas.",
      "trackrecord": "Décadas de trayectoria comprobada en la industria bancaria.",
      "network": "Red global de sucursales/ATMs para fácil acceso.",
      "service": "Servicio al cliente 24/7 con gerentes de relaciones dedicados.",
      "advice": "Consejos financieros personalizados de expertos certificados.",
      "rewards": "Recompensas y beneficios exclusivos adaptados al estilo de vida.",
      "approvals": "Aprobaciones rápidas y fácil incorporación para nuevas cuentas.",
      "fees": "Tarifas claras y por adelantado sin cargos ocultos."
    },
    "services": {
      "title": "Nuestros servicios incluyen:",
      "personal": "Banca Personal",
      "investments": "Servicios de Inversión",
      "pension": "Fondos de Pensiones"
    },
    "footer": {
      "contact": "Contáctenos",
      "email": "Correo: <a href=\"mailto:unitedbnk@support.com\">unitedbnk@support.com</a>",
      "copyright": "&copy; 2026 United Bank. Todos los derechos reservados.",
      "privacy": "Política de Privacidad",
      "terms": "Términos del Servicio",
      "contactLink": "Contáctenos"
    },
    "signin": {
      "title": "Inicia sesión en tu cuenta",
      "username": "Nombre de usuario:",
      "password": "Contraseña:",
      "forgot": "¿Olvidaste tu contraseña?",
      "submit": "Iniciar sesión"
    },
    "signup": {
      "title": "Crear una cuenta",
      "tagline": "Banca sin compromiso: su puerta de entrada al prestigio, la seguridad y el crecimiento.",
      "email": "Correo electrónico:",
      "password": "Contraseña:",
      "confirm": "Confirmar contraseña:",
      "submit": "Regístrate",
      "agreement": "Al registrarte, aceptas nuestros <a href=\"\">Términos del Servicio</a> y <a href=\"\">Política de Privacidad</a>."
    },
    "transfer": {
      "senderTitle": "Detalles del Remitente",
      "name": "Nombre:",
      "account": "Número de Cuenta:",
      "mainBalance": "Saldo Principal:",
      "savingsBalance": "Saldo de Ahorros:",
      "cardBalance": "Saldo de Tarjeta:",
      "title": "Transferir Fondos",
      "desc": "Envía dinero de forma segura a otra cuenta bancaria.",
      "fromAccount": "Selecciona Cuenta",
      "select": "Seleccionar Cuenta",
      "mainAcc": "Cuenta Principal",
      "savingsAcc": "Cuenta de Ahorros",
      "cardAcc": "Tarjeta",
      "recipientBank": "Banco del Destinatario",
      "recipientName": "Nombre del Destinatario",
      "recipientAccount": "Número de Cuenta del Destinatario",
      "amount": "Monto ($)",
      "description": "Descripción",
      "send": "Enviar",
      "pending": "Transacción pendiente, esperando aprobación"
    },
    "trans": {
      "title": "Historial de Transacciones",
      "desc": "Ver toda tu actividad de cuenta.",
      "filter": "Filtrar Transacciones",
      "allTypes": "Todos los Tipos",
      "credit": "Crédito",
      "debit": "Débito",
      "allStatus": "Todos los Estados",
      "completed": "Completado",
      "pending": "Pendiente",
      "failed": "Fallido",
      "apply": "Aplicar Filtro",
      "allTrans": "Todas las Transacciones"
    },
    "dashboard": {
      "welcome": "Bienvenido de vuelta",
      "summary": "Tu resumen financiero de un vistazo.",
      "accountBal": "Saldo de Cuenta",
      "savingsBal": "Saldo de Ahorros",
      "creditCard": "Tarjeta de Crédito",
      "due": "debido",
      "quickActions": "Acciones Rápidas",
      "transfer": "Transferir Fondos",
      "payBills": "Pagar Facturas",
      "viewAccounts": "Ver Cuentas",
      "recentTrans": "Transacciones Recientes"
    },
    "about": {
      "title": "Sobre United Bank"
    },
    "receipt": {
      "headquarters": "Sede Corporativa",
      "title": "RECIBO DE TRANSACCIÓN OFICIAL",
      "subtitle": "Confirmación Generada por el Sistema",
      "ref": "Referencia de Transacción:",
      "email": "Correo del Remitente:",
      "fromAccount": "Desde la Cuenta:",
      "recipientName": "Nombre del Destinatario:",
      "recipientBank": "Banco del Destinatario:",
      "recipientAccount": "Cuenta del Destinatario:",
      "amount": "Monto:",
      "description": "Descripción:",
      "date": "Fecha y Hora:",
      "status": "Estado:",
      "signatory": "Firmante Autorizado",
      "verified": "VERIFICADO DIGITALMENTE",
      "legal": "Este documento es generado electrónicamente por el sistema bancario de United Bank. No se requiere firma física. Si no autorizaste esta transacción, contacta a nuestro servicio al cliente de inmediato.",
      "download": "Descargar Recibo"
    },
    "admin": {
      "dashboard": "Panel",
      "users": "Usuarios",
      "transactions": "Transacciones",
      "reports": "Reportes",
      "settings": "Configuración",
      "welcome": "Bienvenido, Administrador",
      "overview": "Descripción general rápida del estado del sistema bancario."
    },
    "adminTrans": {
      "title": "Panel de Administración - Todas las Transacciones"
    },
    "userDetails": {
      "title": "Detalles del Usuario"
    },
    "userList": {
      "title": "Todos los Usuarios Registrados",
      "desc": "A continuación se muestra la lista de todos los usuarios en el sistema."
    }
  },

  fr: {
    "nav": {
      "signin": "Se connecter",
      "signup": "S'inscrire",
      "about": "À propos",
      "services": "Services",
      "support": "Assistance",
      "dashboard": "Tableau de bord",
      "transactions": "Transactions",
      "transaction": "Transaction",
      "transfer": "Virement",
      "transfers": "Virements",
      "settings": "Paramètres",
      "logout": "Déconnexion"
    },
    "lang": {
      "label": "Langue :"
    },
    "offers": {
      "title": "Ce que nous offrons :",
      "encryption": "Chiffrement avancé pour sécuriser les transactions.",
      "monitoring": "Surveillance de fraude en temps réel avec alertes instantanées.",
      "trackrecord": "Des décennies de parcours prouvé dans l'industrie bancaire.",
      "network": "Réseau mondial de succursales/ATM pour un accès facile.",
      "service": "Service client 24h/24 et 7j/7 avec des gestionnaires de relations dédiés.",
      "advice": "Conseils financiers personnalisés d'experts certifiés.",
      "rewards": "Récompenses et avantages exclusifs adaptés au style de vie.",
      "approvals": "Approvals rapides et intégration facile pour les nouveaux comptes.",
      "fees": "Frais clairs et à l'avance sans frais cachés."
    },
    "services": {
      "title": "Nos services comprennent :",
      "personal": "Services bancaires personnels",
      "investments": "Services d'investissement",
      "pension": "Fonds de pension"
    },
    "footer": {
      "contact": "Contactez-nous",
      "email": "E-mail : <a href=\"mailto:unitedbnk@support.com\">unitedbnk@support.com</a>",
      "copyright": "&copy; 2026 United Bank. Tous droits réservés.",
      "privacy": "Politique de confidentialité",
      "terms": "Conditions d'utilisation",
      "contactLink": "Contactez-nous"
    },
    "signin": {
      "title": "Connectez-vous à votre compte",
      "username": "Nom d'utilisateur:",
      "password": "Mot de passe:",
      "forgot": "Mot de passe oublié ?",
      "submit": "Se connecter"
    },
    "signup": {
      "title": "Créer un compte",
      "tagline": "Banque sans compromis : votre porte d'entrée vers le prestige, la sécurité et la croissance.",
      "email": "E-mail :",
      "password": "Mot de passe:",
      "confirm": "Confirmer le mot de passe:",
      "submit": "S'inscrire",
      "agreement": "En vous inscrivant, vous acceptez nos <a href=\"\">Conditions d'utilisation</a> et <a href=\"\">Politique de confidentialité</a>."    },
    "transfer": {
      "senderTitle": "Détails de l'Expéditeur",
      "name": "Nom :",
      "account": "Numéro de Compte :",
      "mainBalance": "Solde Principal :",
      "savingsBalance": "Solde d'Épargne :",
      "cardBalance": "Solde de Carte :",
      "title": "Effectuer un Virement",
      "desc": "Envoyez de l'argent de manière sécurisée à un autre compte bancaire.",
      "fromAccount": "Choisir un Compte",
      "select": "Sélectionner un Compte",
      "mainAcc": "Compte Principal",
      "savingsAcc": "Compte d'Épargne",
      "cardAcc": "Carte",
      "recipientBank": "Banque du Bénéficiaire",
      "recipientName": "Nom du Bénéficiaire",
      "recipientAccount": "Numéro de Compte du Bénéficiaire",
      "amount": "Montant ($)",
      "description": "Description",
      "send": "Envoyer",
      "pending": "Transaction en attente, en attente d'approbation"
    },
    "trans": {
      "title": "Historique des Transactions",
      "desc": "Consultez toute votre activité de compte.",
      "filter": "Filtrer les Transactions",
      "allTypes": "Tous les Types",
      "credit": "Crédit",
      "debit": "Débit",
      "allStatus": "Tous les Statuts",
      "completed": "Complété",
      "pending": "En Attente",
      "failed": "Échoué",
      "apply": "Appliquer le Filtre",
      "allTrans": "Toutes les Transactions"
    },
    "dashboard": {
      "welcome": "Bienvenue de retour",
      "summary": "Votre résumé financier d'un coup d'œil.",
      "accountBal": "Solde du Compte",
      "savingsBal": "Solde d'Épargne",
      "creditCard": "Carte de Crédit",
      "due": "dû",
      "quickActions": "Actions Rapides",
      "transfer": "Effectuer un Virement",
      "payBills": "Payer les Factures",
      "viewAccounts": "Voir les Comptes",
      "recentTrans": "Transactions Récentes"
    },
    "about": {
      "title": "À propos de United Bank"
    },
    "receipt": {
      "headquarters": "Siège Social",
      "title": "REÇU DE TRANSACTION OFFICIEL",
      "subtitle": "Confirmation Générée par le Système",
      "ref": "Référence de Transaction :",
      "email": "E-mail de l'Expéditeur :",
      "fromAccount": "Du Compte :",
      "recipientName": "Nom du Bénéficiaire :",
      "recipientBank": "Banque du Bénéficiaire :",
      "recipientAccount": "Compte du Bénéficiaire :",
      "amount": "Montant :",
      "description": "Description :",
      "date": "Date et Heure :",
      "status": "Statut :",
      "signatory": "Signataire Autorisé",
      "verified": "VÉRIFIÉ NUMÉRIQUEMENT",
      "legal": "Ce document est généré électroniquement par le système bancaire de United Bank. Aucune signature physique n'est requise. Si vous n'avez pas autorisé cette transaction, contactez immédiatement notre support client.",
      "download": "Télécharger le Reçu"
    },
    "admin": {
      "dashboard": "Tableau de bord",
      "users": "Utilisateurs",
      "transactions": "Transactions",
      "reports": "Rapports",
      "settings": "Paramètres",
      "welcome": "Bienvenue, Administrateur",
      "overview": "Aperçu rapide du statut du système bancaire."
    },
    "adminTrans": {
      "title": "Panneau d'Administration - Toutes les Transactions"
    },
    "userDetails": {
      "title": "Détails de l'Utilisateur"
    },
    "userList": {
      "title": "Tous les Utilisateurs Enregistrés",
      "desc": "Voici la liste de tous les utilisateurs du système."
    }
  },

  pt: {
    "nav": {
      "signin": "Iniciar sessão",
      "signup": "Registar-se",
      "about": "Sobre nós",
      "services": "Serviços",
      "support": "Suporte",
      "dashboard": "Painel",
      "transactions": "Transações",
      "transaction": "Transação",
      "transfer": "Transferir",
      "transfers": "Transferências",
      "settings": "Definições",
      "logout": "Terminar sessão"
    },
    "lang": {
      "label": "Idioma:"
    },
    "offers": {
      "title": "O que oferecemos:",
      "encryption": "Encriptação avançada para manter as transações seguras.",
      "monitoring": "Monitorização de fraude em tempo real com alertas instantâneos.",
      "trackrecord": "Décadas de experiência comprovada no setor bancário.",
      "network": "Rede global de agências/ATM para acesso fácil.",
      "service": "Atendimento 24/7 com gestores dedicados.",
      "advice": "Conselho financeiro personalizado por especialistas certificados.",
      "rewards": "Recompensas e benefícios exclusivos adaptados ao seu estilo de vida.",
      "approvals": "Aprovações rápidas e onboarding simples para novas contas.",
      "fees": "Taxas claras desde o início, sem encargos ocultos."
    },
    "services": {
      "title": "Os nossos serviços incluem:",
      "personal": "Banca Pessoal",
      "investments": "Serviços de Investimento",
      "pension": "Fundos de Pensão"
    },
    "footer": {
      "contact": "Contacte-nos",
      "email": "Email: <a href=\"mailto:unitedbnk@support.com\">unitedbnk@support.com</a>",
      "copyright": "&copy; 2026 United Bank. Todos os direitos reservados.",
      "privacy": "Política de Privacidade",
      "terms": "Termos de Serviço",
      "contactLink": "Contacte-nos"
    },
    "signin": {
      "title": "Inicie sessão na sua conta",
      "username": "Nome de utilizador:",
      "password": "Palavra-passe:",
      "forgot": "Esqueceu-se da palavra-passe?",
      "submit": "Iniciar sessão"
    },
    "signup": {
      "title": "Criar uma conta",
      "tagline": "Banca sem compromisso — a sua porta para segurança e crescimento.",
      "email": "Email:",
      "password": "Palavra-passe:",
      "confirm": "Confirmar palavra-passe:",
      "submit": "Registar-se",
      "agreement": "Ao registar-se, concorda com os nossos <a href=\">Termos de Serviço</a> e <a href=\">Política de Privacidade</a>."
    },
    "transfer": {
      "senderTitle": "Detalhes do Remetente",
      "name": "Nome:",
      "account": "Número de Conta:",
      "mainBalance": "Saldo Principal:",
      "savingsBalance": "Saldo Poupanças:",
      "cardBalance": "Saldo do Cartão:",
      "title": "Transferir Fundos",
      "desc": "Envie dinheiro de forma segura para outra conta bancária.",
      "fromAccount": "Escolher Conta",
      "select": "Selecionar Conta",
      "mainAcc": "Conta Principal",
      "savingsAcc": "Conta Poupança",
      "cardAcc": "Cartão",
      "recipientBank": "Banco do Beneficiário",
      "recipientName": "Nome do Beneficiário",
      "recipientAccount": "Número de Conta do Beneficiário",
      "amount": "Montante ($)",
      "description": "Descrição",
      "send": "Enviar",
      "pending": "Transação pendente, à espera de aprovação"
    },
    "trans": {
      "title": "Histórico de Transações",
      "desc": "Veja toda a atividade da sua conta.",
      "filter": "Filtrar Transações",
      "allTypes": "Todos os Tipos",
      "credit": "Crédito",
      "debit": "Débito",
      "allStatus": "Todos os Estados",
      "completed": "Concluído",
      "pending": "Pendente",
      "failed": "Falhado",
      "apply": "Aplicar Filtro",
      "allTrans": "Todas as Transações"
    },
    "dashboard": {
      "welcome": "Bem-vindo de volta",
      "summary": "O seu resumo financeiro de um relance.",
      "accountBal": "Saldo da Conta",
      "savingsBal": "Saldo Poupanças",
      "creditCard": "Cartão de Crédito",
      "due": "vencimento",
      "quickActions": "Ações Rápidas",
      "transfer": "Transferir Fundos",
      "payBills": "Pagar Contas",
      "viewAccounts": "Ver Contas",
      "recentTrans": "Transações Recentes"
    },
    "about": { "title": "Sobre a United Bank" },
    "receipt": {
      "headquarters": "Sede Corporativa",
      "title": "RECIBO OFICIAL DE TRANSAÇÃO",
      "subtitle": "Confirmação Gerada pelo Sistema",
      "ref": "Referência de Transação:",
      "email": "Email do Remetente:",
      "fromAccount": "Da Conta:",
      "recipientName": "Nome do Beneficiário:",
      "recipientBank": "Banco do Beneficiário:",
      "recipientAccount": "Conta do Beneficiário:",
      "amount": "Montante:",
      "description": "Descrição:",
      "date": "Data e Hora:",
      "status": "Estado:",
      "signatory": "Signatário Autorizado",
      "verified": "VERIFICADO DIGITALMENTE",
      "legal": "Este documento é gerado eletronicamente pelo sistema bancário da United Bank. Não é necessária assinatura física. Se não autorizou esta transação, contacte o suporte imediatamente.",
      "download": "Descarregar Recibo"
    },
    "admin": {
      "dashboard": "Painel",
      "users": "Utilizadores",
      "transactions": "Transações",
      "reports": "Relatórios",
      "settings": "Definições",
      "welcome": "Bem-vindo, Admin",
      "overview": "Visão geral rápida do estado do sistema bancário."
    },
    "adminTrans": { "title": "Painel Admin - Todas as Transações" },
    "userDetails": { "title": "Detalhes do Utilizador" },
    "userList": { "title": "Todos os Utilizadores Registados", "desc": "Abaixo está a lista de todos os utilizadores do sistema." }
  },

  "pt-BR": {
    "nav": {
      "signin": "Entrar",
      "signup": "Cadastrar-se",
      "about": "Sobre nós",
      "services": "Serviços",
      "support": "Suporte",
      "dashboard": "Painel",
      "transactions": "Transações",
      "transaction": "Transação",
      "transfer": "Transferir",
      "transfers": "Transferências",
      "settings": "Configurações",
      "logout": "Sair"
    },
    "lang": { "label": "Idioma:" },
    "offers": {
      "title": "O que oferecemos:",
      "encryption": "Criptografia avançada para manter as transações seguras.",
      "monitoring": "Monitoramento de fraude em tempo real com alertas instantâneos.",
      "trackrecord": "Décadas de experiência comprovada no setor bancário.",
      "network": "Rede global de agências/ATMs para fácil acesso.",
      "service": "Atendimento 24/7 com gerentes dedicados.",
      "advice": "Orientação financeira personalizada por especialistas certificados.",
      "rewards": "Recompensas e benefícios exclusivos adaptados ao seu estilo de vida.",
      "approvals": "Aprovações rápidas e onboarding simples para novas contas.",
      "fees": "Taxas claras desde o início, sem cobranças ocultas."
    },
    "services": { "title": "Nossos serviços incluem:", "personal": "Banca Pessoal", "investments": "Serviços de Investimento", "pension": "Fundos de Pensão" },
    "footer": { "contact": "Fale Conosco", "email": "Email: <a href=\"mailto:unitedbnk@support.com\">unitedbnk@support.com</a>", "copyright": "&copy; 2026 United Bank. Todos os direitos reservados.", "privacy": "Política de Privacidade", "terms": "Termos de Serviço", "contactLink": "Fale Conosco" },
    "signin": { "title": "Acesse sua conta", "username": "Usuário:", "password": "Senha:", "forgot": "Esqueceu a senha?", "submit": "Entrar" },
    "signup": { "title": "Criar uma Conta", "tagline": "Banco sem compromisso — seu caminho para segurança e crescimento.", "email": "Email:", "password": "Senha:", "confirm": "Confirmar Senha:", "submit": "Cadastrar-se", "agreement": "Ao se cadastrar, você concorda com nossos <a href=\">Termos de Serviço</a> e <a href=\">Política de Privacidade</a>." },
    "transfer": { "senderTitle": "Dados do Remetente", "name": "Nome:", "account": "Número da Conta:", "mainBalance": "Saldo Principal:", "savingsBalance": "Saldo Poupança:", "cardBalance": "Saldo do Cartão:", "title": "Transferir Fundos", "desc": "Envie dinheiro com segurança para outra conta bancária.", "fromAccount": "Escolher Conta", "select": "Selecionar Conta", "mainAcc": "Conta Principal", "savingsAcc": "Conta Poupança", "cardAcc": "Cartão", "recipientBank": "Banco do Destinatário", "recipientName": "Nome do Destinatário", "recipientAccount": "Número da Conta do Destinatário", "amount": "Valor ($)", "description": "Descrição", "send": "Enviar", "pending": "Transação pendente, aguardando aprovação" },
    "trans": { "title": "Histórico de Transações", "desc": "Veja todas as atividades da sua conta.", "filter": "Filtrar Transações", "allTypes": "Todos os Tipos", "credit": "Crédito", "debit": "Débito", "allStatus": "Todos os Status", "completed": "Concluído", "pending": "Pendente", "failed": "Falhou", "apply": "Aplicar Filtro", "allTrans": "Todas as Transações" },
    "dashboard": { "welcome": "Bem-vindo de volta", "summary": "Seu resumo financeiro em um piscar de olhos.", "accountBal": "Saldo da Conta", "savingsBal": "Saldo Poupança", "creditCard": "Cartão de Crédito", "due": "vencimento", "quickActions": "Ações Rápidas", "transfer": "Transferir Fundos", "payBills": "Pagar Contas", "viewAccounts": "Ver Contas", "recentTrans": "Transações Recentes" },
    "about": { "title": "Sobre United Bank" },
    "receipt": { "headquarters": "Matriz", "title": "RECIBO OFICIAL DE TRANSAÇÃO", "subtitle": "Confirmação Gerada pelo Sistema", "ref": "Referência da Transação:", "email": "Email do Remetente:", "fromAccount": "Da Conta:", "recipientName": "Nome do Destinatário:", "recipientBank": "Banco do Destinatário:", "recipientAccount": "Conta do Destinatário:", "amount": "Valor:", "description": "Descrição:", "date": "Data e Hora:", "status": "Status:", "signatory": "Assinatura Autorizada", "verified": "VERIFICADO DIGITALMENTE", "legal": "Este documento é gerado eletronicamente pelo sistema bancário da United Bank. Não é necessária assinatura física. Se não autorizou esta transação, contate o suporte imediatamente.", "download": "Baixar Recibo" },
    "admin": { "dashboard": "Painel", "users": "Usuários", "transactions": "Transações", "reports": "Relatórios", "settings": "Configurações", "welcome": "Bem-vindo, Admin", "overview": "Visão geral rápida do estado do sistema bancário." },
    "adminTrans": { "title": "Painel Admin - Todas as Transações" },
    "userDetails": { "title": "Detalhes do Usuário" },
    "userList": { "title": "Todos os Usuários Registrados", "desc": "Abaixo está a lista de todos os usuários do sistema." }
  },

  pl: {
    "nav": {
      "signin": "Zaloguj się",
      "signup": "Zarejestruj się",
      "about": "O nas",
      "services": "Usługi",
      "support": "Wsparcie",
      "dashboard": "Panel",
      "transactions": "Transakcje",
      "transaction": "Transakcja",
      "transfer": "Przelew",
      "transfers": "Przelewy",
      "settings": "Ustawienia",
      "logout": "Wyloguj"
    },
    "lang": { "label": "Język:" },
    "offers": {
      "title": "Co oferujemy:",
      "encryption": "Zaawansowane szyfrowanie chroniące transakcje.",
      "monitoring": "Monitorowanie oszustw w czasie rzeczywistym z natychmiastowymi alertami.",
      "trackrecord": "Dziesięciolecia sprawdzonego doświadczenia w sektorze bankowym.",
      "network": "Globalna sieć oddziałów/ATM dla łatwego dostępu.",
      "service": "Obsługa klienta 24/7 z dedykowanymi menedżerami.",
      "advice": "Spersonalizowane porady finansowe od certyfikowanych ekspertów.",
      "rewards": "Ekskluzywne nagrody i korzyści dopasowane do stylu życia.",
      "approvals": "Szybkie zatwierdzenia i proste rozpoczęcie dla nowych kont.",
      "fees": "Przejrzyste opłaty z góry, bez ukrytych kosztów."
    },
    "services": { "title": "Nasze usługi obejmują:", "personal": "Bankowość osobista", "investments": "Usługi inwestycyjne", "pension": "Fundusze emerytalne" },
    "footer": { "contact": "Skontaktuj się", "email": "Email: <a href=\"mailto:unitedbnk@support.com\">unitedbnk@support.com</a>", "copyright": "&copy; 2026 United Bank. Wszelkie prawa zastrzeżone.", "privacy": "Polityka prywatności", "terms": "Warunki usługi", "contactLink": "Skontaktuj się" },
    "signin": { "title": "Zaloguj się na swoje konto", "username": "Nazwa użytkownika:", "password": "Hasło:", "forgot": "Zapomniałeś hasła?", "submit": "Zaloguj" },
    "signup": { "title": "Załóż konto", "tagline": "Bankowość bez kompromisów — Twój dostęp do bezpieczeństwa i wzrostu.", "email": "Email:", "password": "Hasło:", "confirm": "Potwierdź hasło:", "submit": "Zarejestruj się", "agreement": "Rejestrując się zgadzasz się z naszymi <a href=\">Warunkami usługi</a> i <a href=\">Polityką prywatności</a>." },
    "transfer": { "senderTitle": "Dane nadawcy", "name": "Imię i nazwisko:", "account": "Numer konta:", "mainBalance": "Saldo główne:", "savingsBalance": "Saldo oszczędności:", "cardBalance": "Saldo karty:", "title": "Przelew środków", "desc": "Wyślij pieniądze bezpiecznie na inne konto bankowe.", "fromAccount": "Wybierz konto", "select": "Wybierz konto", "mainAcc": "Konto główne", "savingsAcc": "Konto oszczędnościowe", "cardAcc": "Karta", "recipientBank": "Bank odbiorcy", "recipientName": "Imię odbiorcy", "recipientAccount": "Numer konta odbiorcy", "amount": "Kwota ($)", "description": "Opis", "send": "Wyślij", "pending": "Transakcja w toku, oczekuje na zatwierdzenie" },
    "trans": { "title": "Historia transakcji", "desc": "Zobacz całą aktywność swojego konta.", "filter": "Filtruj transakcje", "allTypes": "Wszystkie typy", "credit": "Kredyt", "debit": "Debet", "allStatus": "Wszystkie statusy", "completed": "Zakończone", "pending": "Oczekujące", "failed": "Nieudane", "apply": "Zastosuj filtr", "allTrans": "Wszystkie transakcje" },
    "dashboard": { "welcome": "Witamy ponownie", "summary": "Twoje podsumowanie finansowe w skrócie.", "accountBal": "Saldo konta", "savingsBal": "Saldo oszczędności", "creditCard": "Karta kredytowa", "due": "należne", "quickActions": "Szybkie akcje", "transfer": "Przelej środki", "payBills": "Opłać rachunki", "viewAccounts": "Pokaż konta", "recentTrans": "Ostatnie transakcje" },
    "about": { "title": "O United Bank" },
    "receipt": { "headquarters": "Siedziba", "title": "OFICJALNY POKWITOWANIE TRANSAKCJI", "subtitle": "Potwierdzenie wygenerowane systemowo", "ref": "Referencja transakcji:", "email": "Email nadawcy:", "fromAccount": "Z konta:", "recipientName": "Nazwa odbiorcy:", "recipientBank": "Bank odbiorcy:", "recipientAccount": "Konto odbiorcy:", "amount": "Kwota:", "description": "Opis:", "date": "Data i godzina:", "status": "Status:", "signatory": "Upoważniony podpis", "verified": "ZWERYFIKOWANE CYFROWO", "legal": "Ten dokument jest generowany elektronicznie przez system bankowy United Bank. Nie jest wymagana podpis fizyczny. Jeśli nie autoryzowałeś tej transakcji, skontaktuj się z obsługą klienta natychmiast.", "download": "Pobierz potwierdzenie" },
    "admin": { "dashboard": "Panel", "users": "Użytkownicy", "transactions": "Transakcje", "reports": "Raporty", "settings": "Ustawienia", "welcome": "Witamy, Administrator", "overview": "Szybki przegląd stanu systemu bankowego." },
    "adminTrans": { "title": "Panel Admin - Wszystkie transakcje" },
    "userDetails": { "title": "Szczegóły użytkownika" },
    "userList": { "title": "Wszyscy zarejestrowani użytkownicy", "desc": "Poniżej lista wszystkich użytkowników w systemie." }
  },

  de: {
    "nav": {
      "signin": "Anmelden",
      "signup": "Registrieren",
      "about": "Über uns",
      "services": "Dienstleistungen",
      "support": "Support",
      "dashboard": "Übersicht",
      "transactions": "Transaktionen",
      "transaction": "Transaktion",
      "transfer": "Überweisen",
      "transfers": "Überweisungen",
      "settings": "Einstellungen",
      "logout": "Abmelden"
    },
    "lang": { "label": "Sprache:" },
    "offers": {
      "title": "Unser Angebot:",
      "encryption": "Fortschrittliche Verschlüsselung zum Schutz von Transaktionen.",
      "monitoring": "Echtzeit-Fraud-Monitoring mit sofortigen Warnungen.",
      "trackrecord": "Jahrzehntelange nachgewiesene Erfahrung in der Bankenbranche.",
      "network": "Globales Netz aus Filialen/ATMs für einfachen Zugang.",
      "service": "24/7-Kundendienst mit persönlichen Betreuern.",
      "advice": "Personalisierte Finanzberatung durch zertifizierte Experten.",
      "rewards": "Exklusive Prämien & Vorteile, abgestimmt auf Ihren Lebensstil.",
      "approvals": "Schnelle Genehmigungen & einfache Kontoeröffnung.",
      "fees": "Klare, transparente Gebühren ohne versteckte Kosten."
    },
    "services": { "title": "Unsere Dienstleistungen umfassen:", "personal": "Privatkundengeschäft", "investments": "Investmentdienstleistungen", "pension": "Pensionsfonds" },
    "footer": { "contact": "Kontakt", "email": "Email: <a href=\"mailto:unitedbnk@support.com\">unitedbnk@support.com</a>", "copyright": "&copy; 2026 United Bank. Alle Rechte vorbehalten.", "privacy": "Datenschutz", "terms": "Nutzungsbedingungen", "contactLink": "Kontakt" },
    "signin": { "title": "Melden Sie sich bei Ihrem Konto an", "username": "Benutzername:", "password": "Passwort:", "forgot": "Passwort vergessen?", "submit": "Anmelden" },
    "signup": { "title": "Ein Konto erstellen", "tagline": "Banking ohne Kompromisse — Ihr Zugang zu Sicherheit und Wachstum.", "email": "Email:", "password": "Passwort:", "confirm": "Passwort bestätigen:", "submit": "Registrieren", "agreement": "Mit der Registrierung stimmen Sie unseren <a href=\">Nutzungsbedingungen</a> und der <a href=\">Datenschutzerklärung</a> zu." },
    "transfer": { "senderTitle": "Absenderdetails", "name": "Name:", "account": "Kontonummer:", "mainBalance": "Hauptguthaben:", "savingsBalance": "Sparguthaben:", "cardBalance": "Kartenkonto:", "title": "Geld überweisen", "desc": "Senden Sie Geld sicher an ein anderes Bankkonto.", "fromAccount": "Konto wählen", "select": "Konto auswählen", "mainAcc": "Hauptkonto", "savingsAcc": "Sparkonto", "cardAcc": "Karte", "recipientBank": "Empfängerbank", "recipientName": "Empfängername", "recipientAccount": "Empfängerkontonummer", "amount": "Betrag ($)", "description": "Beschreibung", "send": "Senden", "pending": "Transaktion ausstehend, wartet auf Genehmigung" },
    "trans": { "title": "Transaktionsverlauf", "desc": "Sehen Sie alle Aktivitäten Ihres Kontos.", "filter": "Transaktionen filtern", "allTypes": "Alle Typen", "credit": "Gutschrift", "debit": "Belastung", "allStatus": "Alle Status", "completed": "Abgeschlossen", "pending": "Ausstehend", "failed": "Fehlgeschlagen", "apply": "Filter anwenden", "allTrans": "Alle Transaktionen" },
    "dashboard": { "welcome": "Willkommen zurück", "summary": "Ihre finanzielle Übersicht auf einen Blick.", "accountBal": "Kontostand", "savingsBal": "Sparguthaben", "creditCard": "Kreditkarte", "due": "fällig", "quickActions": "Schnellaktionen", "transfer": "Geld überweisen", "payBills": "Rechnungen bezahlen", "viewAccounts": "Konten anzeigen", "recentTrans": "Letzte Transaktionen" },
    "about": { "title": "Über United Bank" },
    "receipt": { "headquarters": "Hauptsitz", "title": "OFFIZIELLER TRANSAKTIONSBELEG", "subtitle": "Systemgenerierte Bestätigung", "ref": "Transaktionsreferenz:", "email": "Absender Email:", "fromAccount": "Von Konto:", "recipientName": "Empfängername:", "recipientBank": "Empfängerbank:", "recipientAccount": "Empfängerkonto:", "amount": "Betrag:", "description": "Beschreibung:", "date": "Datum & Uhrzeit:", "status": "Status:", "signatory": "Bevollmächtigter Unterzeichner", "verified": "DIGITAL VERIFIZIERT", "legal": "Dieses Dokument wurde elektronisch vom Kernbankensystem der United Bank erzeugt. Keine physische Unterschrift erforderlich. Falls Sie diese Transaktion nicht autorisiert haben, kontaktieren Sie sofort den Kundensupport.", "download": "Beleg herunterladen" },
    "admin": { "dashboard": "Übersicht", "users": "Benutzer", "transactions": "Transaktionen", "reports": "Berichte", "settings": "Einstellungen", "welcome": "Willkommen, Admin", "overview": "Kurzübersicht zum Systemstatus der Bank." },
    "adminTrans": { "title": "Admin-Bereich - Alle Transaktionen" },
    "userDetails": { "title": "Benutzerdetails" },
    "userList": { "title": "Alle registrierten Benutzer", "desc": "Unten ist die Liste aller Benutzer im System." }
  }
};

// helper to walk nested objects by dot notation key
function translateKey(obj, key) {
  return key.split('.').reduce((o, k) => (o && o[k] !== undefined ? o[k] : null), obj);
}

function applyTranslations(lang) {
  const nodes = document.querySelectorAll('[data-i18n]');
  nodes.forEach(node => {
    const key = node.getAttribute('data-i18n');
    const value = translateKey(translations[lang], key) || translateKey(translations.en, key) || '';
    node.innerHTML = value;
  });
}

function detectLanguage() {
  // first try navigator.language
  let lang = navigator.language && navigator.language.split('-')[0];
  if (lang && translations[lang]) return lang;

  // try geolocation-based lookup
  if (navigator.geolocation) {
    return new Promise(resolve => {
      navigator.geolocation.getCurrentPosition(
        pos => {
          const { latitude, longitude } = pos.coords;
          // simple country lookup using fetch to a free API
          fetch(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${latitude}&longitude=${longitude}&localityLanguage=en`)
            .then(r => r.json())
            .then(data => {
              const cc = (data.countryCode || '').toLowerCase();
              resolve(getLangFromCountryCode(cc));
            })
            .catch(() => resolve('en')); // fallback
        },
        () => resolve('en'),
        { timeout: 5000 }
      );
    });
  }

  // fallback to IP-based if geolocation not available
  return fetch('https://ipapi.co/json/')
    .then(r => r.json())
    .then(data => getLangFromCountryCode((data.country_code || '').toLowerCase()))
    .catch(() => 'en');
}

function getLangFromCountryCode(cc) {
  const map = {
    fr: 'fr',
    es: 'es',
    mx: 'es',
    ca: 'fr',
    us: 'en',
    gb: 'en',
    de: 'de',
    pt: 'pt',
    br: 'pt-BR',
    pl: 'pl'
  };
  return map[cc] || 'en';
}

// user can manually change
function setupSelector(lang) {
  const sel = document.getElementById('language-select');
  if (!sel) return;
  sel.value = lang;
  sel.addEventListener('change', e => {
    const chosen = e.target.value;
    applyTranslations(chosen);
    localStorage.setItem('preferredLang', chosen);
  });
}

// initialization
function initTranslations() {
  const stored = localStorage.getItem('preferredLang');
  if (stored && translations[stored]) {
    applyTranslations(stored);
    setupSelector(stored);
    return;
  }

  const detected = detectLanguage();
  if (detected instanceof Promise) {
    detected.then(lang => {
      applyTranslations(lang);
      setupSelector(lang);
    });
  } else {
    applyTranslations(detected);
    setupSelector(detected);
  }
}

// run once DOM is ready
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', initTranslations);
} else {
  initTranslations();
}
